//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace superearthcommvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRequest
    {
        public string Name { get; set; }
        public System.Guid ID { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool CanText { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> HasEngaged { get; set; }
        public string Company { get; set; }
    }
}
