//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace superearthcommvc.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperEarthComEntities1 : DbContext
    {
        public SuperEarthComEntities1()
            : base("name=SuperEarthComEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactRequest> ContactRequests { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<SurveyResponse> SurveyResponses { get; set; }
    }
}
